### ISSUE TITLE
Inhalte werden nicht gerendert

### ISSUE THREAD

**Issue by gisma** [ThomasBeier/src_GIS2021-22#1]
@ThomasBeier 
Falls es noch Probleme bei rendern der Inhalte gibt bitte aus dem yaml frontmatter  die folgenden items löschen:
```yaml
output:
  blogdown::html_page:
    keep_md: yes
```
evtl. auch den `source` Befehl wie folgt erweitertn
`source(file.path(envimaR::alternativeEnvi(root_folder = root_folder),"src/000-rspatial-setup.R"),local = knitr::knit_global())`

btw i like the title images...
